sudo: required
services:
  - docker

before_install:
  - docker build -t kevinchia/docker-react -f Dockerfile.dev .

scripts:
  - docker -e CI=true run kevinchia/docker-react npm run test -- --coverage 
