sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kevinchia/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true kevinchia/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-058443077170"
  bucket_path: "docker-react"
  on:
    - main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
