sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kevinchia/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true kevinchia/docker-react npm run test -- --coverage
